services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: bizhub/bizkeeper:v1
    container_name: webapi
    ports:
    - "7000:8080"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=BizKeeper;User=Gala;Password=cat;TrustServerCertificate=True
    networks:
     - my_network

networks:
  my_network:
    driver: bridge